#!/bin/bash

# temp="/opt/dcptools/temp"

# protected_disks='nvme|sda|sdb|sdc'
# default_sources_dir="/mnt/nvme0n1p1/DCPsources"

# protected_disks='nvme|sda'
# default_sources_dir="/mnt/nvme0n1p2/DCPs"